package com.unime.securegame.service;

import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;
import org.springframework.http.*;
import java.util.*;

@Service
public class LlmService {

    // Using Gemini API as the LLM provider. 
    // Reads from environment variable. If not set, uses local mock generation.
    private String geminiApiKey = System.getenv("GEMINI_API_KEY");

    public String generateScenario(String topic, String type) {
        if (geminiApiKey == null || geminiApiKey.isEmpty()) {
            return mockResponse(topic, type);
        }
        
        try {
            RestTemplate restTemplate = new RestTemplate();
            String url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=" + geminiApiKey;
            
            String prompt = "You are an expert cybersecurity instructor. Generate a strictly formatted JSON array/object for a game module of type '" + type + "' about the topic '" + topic + "'. ";
            if (type.equals("crypto")) {
                prompt += "Format MUST BE an array of objects: [{\"q\": \"question text\", \"opts\": [\"A\", \"B\", \"C\", \"D\"], \"ans\": 1, \"expl\": \"explanation\"}]. Return ONLY the raw JSON array, without markdown blocks.";
            } else if (type.equals("phishing")) {
                prompt += "Format MUST BE an array of objects: [{\"url\": \"http://example.com\", \"safe\": false, \"reason\": \"explanation\"}]. Return ONLY the raw JSON array, without markdown blocks.";
            } else if (type.equals("matching")) {
                prompt += "Format MUST BE a single object: {\"terms\": [\"Term1\", \"Term2\", \"Term3\"], \"defs\": [\"Def1\", \"Def2\", \"Def3\"]}. Return ONLY the raw JSON object, without markdown blocks.";
            }

            String requestBody = "{ \"contents\": [{ \"parts\": [{\"text\": \"" + prompt.replace("\"", "\\\"") + "\"}] }] }";
            
            HttpHeaders headers = new HttpHeaders();
            headers.setContentType(MediaType.APPLICATION_JSON);
            HttpEntity<String> entity = new HttpEntity<>(requestBody, headers);
            
            ResponseEntity<Map> response = restTemplate.postForEntity(url, entity, Map.class);
            Map<String, Object> body = response.getBody();
            List<Map<String, Object>> candidates = (List<Map<String, Object>>) body.get("candidates");
            Map<String, Object> content = (Map<String, Object>) candidates.get(0).get("content");
            List<Map<String, Object>> parts = (List<Map<String, Object>>) content.get("parts");
            String text = (String) parts.get(0).get("text");
            
            return text.replace("```json", "").replace("```", "").trim();
        } catch(Exception e) {
            e.printStackTrace();
            return mockResponse(topic, type);
        }
    }
    
    private String mockResponse(String topic, String type) {
        if (type.equals("crypto")) {
            return "[{\"q\": \"(AI MOCK) Which vulnerability is most common in " + topic + "?\", \"opts\": [\"Buffer Overflow\", \"SQL Injection\", \"XSS\", \"CSRF\"], \"ans\": 1, \"expl\": \"Generated by AI Mock for " + topic + "\"}]";
        } else if (type.equals("phishing")) {
            return "[{\"url\": \"http://mocked-" + topic.replace(" ", "") + ".com/login\", \"safe\": false, \"reason\": \"(AI MOCK) Automatically flagged due to suspicious TLD for " + topic + ".\"}]";
        } else {
            return "{\"terms\": [\"" + topic + " Auth\", \"" + topic + " Enc\"], \"defs\": [\"Mock definition for auth\", \"Mock definition for enc\"]}";
        }
    }
}
